[tool.poetry]
name = "BotAInik"
version = "0.1.0"
description = "RAG to prepare for DS interviews, the project was carried out within the framework of the ITMO discipline Introduction to LLM"
authors = ["Anna Sidorova <anna.pav.sidorova@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.5"
black = "^23.9.1"
pre-commit = "^4.0.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]

[tool.black]
line-length = 99
target-version = ["py310"]
