[tool.poetry]
name = "parsers"
version = "0.1.0"
description = ""
authors = ["GlebIsrailevich <glebusai308@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
bs4 = "^0.0.2"
torch = "^2.5.1"
safetensors = "^0.4.5"
langchain = "^0.3.9"
langchain-text-splitters = "^0.3.2"
langchain-community = "^0.3.9"
langchain-chroma = "^0.1.4"
icecream = "^2.1.3"
langchain-mistralai = "^0.2.3"
sentence-transformers = "^3.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
